ach:
  account: 'Account #: 299912421028'
  bank: Wells Fargo
  routing: 'Routing #: 121000248'
address:
  line1: MEC Energy Services
  line2: 3949 Hwy 8, Suite 110
  line3: New Town, ND 48763
  line4: 'TIN: 753209819'
  line5: null
  line6: null
approvers:
  China:
    COR: "Michael Okamura \u2013 Senior Facility Manager \u2013 EAP COR-B"
    MES: "Christine Rosenquist \u2013 MES Resident Manager"
  Hong Kong:
    COR: "Michael Okamura \u2013 Senior Facility Manager \u2013 EAP COR-B"
    MES: "Christine Rosenquist \u2013 MES Resident Manager"
  Moldova:
    COR: "Akram Elfeki - Senior Facility Manager \u2013 Moscow COR"
    MES: "Kevin Carroll \u2013 MES Resident Manager"
  NATO:
    COR: "Robert Warner \u2013 DOS-COR-M"
    MES: "Dustin Bergee \u2013 MES Resident Manager"
  Russia:
    COR: "Akram Elfeki - Senior Facility Manager \u2013 Moscow COR"
    MES: "Kevin Carroll \u2013 MES Resident Manager"
  Ukraine:
    COR: "Akram Elfeki - Senior Facility Manager \u2013 Moscow COR"
    MES: "Kevin Carroll \u2013 MES Resident Manager"
  Vietnam:
    COR: "Michael Okamura \u2013 Senior Facility Manager \u2013 EAP COR-B"
    MES: "Christine Rosenquist \u2013 MES Resident Manager"
baseYear: '0'
billTo:
  line1: IPP
  line2: GLobal Financial Services Center
  line3: P.O. Box 150008
  line4: 'ATTN: Office of Claims'
  line5: Charleston, SC 29415-5008
  line6: 'Re: Helga Lumpkin'
contractNumber: 19AQMM23C0047
dataStyles:
  Admin:
    style: numberCell
    width: 12
  BillingPeriod:
    style: defaultCell
    width: 25
  CLIN:
    style: defaultCell
    width: 10,
  Category:
    style: defaultCell
    width: 48
  City:
    style: defaultCell
    width: 15
  ContractID:
    style: defaultCell
    width: 20
  Date:
    style: dateCell
    width: 15
  Descr:
    style: defaultCell
    width: 54
  Description:
    style: defaultCell
    width: 25
  EmbeddedAdmin:
    style: numberCell
    width: 12
  Filename:
    style: defaultCell
    width: 25
  Hazard:
    style: currencyCell
    width: 15
  Hazard Pay:
    style: currencyCell
    width: 15
  Hazard Rate:
    style: percentageCell
    width: 12
  Hours:
    style: numberCell
    width: 9
  InvoiceAmount:
    style: currencyCell
    width: 15
  InvoiceNumber:
    style: defaultCell
    width: 20
  Local Holiday:
    style: numberCell
    width: 12
  Location:
    style: defaultCell
    width: 15
  Name:
    style: defaultCell
    width: 18
  Number:
    style: defaultCell
    width: 10
  On-Call OT:
    style: numberCell
    width: 12
  Overtime:
    style: numberCell
    width: 12
  Overtime Rate:
    style: currencyCell
    width: 15
  Percentage:
    style: percentageCell
    width: 10
  Post Rate:
    style: percentageCell
    width: 12
  Posting:
    style: currencyCell
    width: 15
  Posting Pay:
    style: currencyCell
    width: 15
  Rate:
    style: currencyCell
    width: 10
  Regular:
    style: numberCell
    width: 12
  Regular Hours:
    style: numberCell
    width: 12
  Regular Rate:
    style: currencyCell
    width: 12
  Regular Wages:
    style: currencyCell
    width: 15
  Scheduled OT:
    style: numberCell
    width: 12
  State:
    style: defaultCell
    width: 10
  SubCLIN:
    style: defaultCell
    width: 7
  Subtotal:
    style: numberCell
    width: 12
  SummaryDescription:
    style: textCell
    width: 25
  SummaryHours:
    style: numberCell
    width: 12
  SummaryName:
    style: textCell
    width: 18
  SummaryRate:
    style: currencyCell
    width: 8
  SummarySubCLIN:
    style: textCell
    width: 7
  SummaryTotal:
    style: currencyCell
    width: 15
  Task ID:
    style: defaultCell
    width: 8
  Task Name:
    style: defaultCell
    width: 12
  TaskOrder:
    style: defaultCell
    width: 15
  Title:
    style: defaultCell
    width: 28
  Total:
    style: currencyCell
    width: 15
  Total Billing:
    style: currencyCell
    width: 20
  Total Hazard:
    style: currencyCell
    width: 15
  Total Overtime:
    style: currencyCell
    width: 20
  Total Post:
    style: currencyCell
    width: 15
  Total Regular:
    style: currencyCell
    width: 20
  Type:
    style: defaultCell
    width: 10
  Unscheduled OT:
    style: numberCell
    width: 12
  Upcharge:
    style: currencyCell
    width: 15
  Wages:
    style: currencyCell
    width: 15
laborHeaders:
  clin: CLIN
  description: Category
  quantity: Hours
  rate: Rate
  total: Amount
  type: Name
nextInvoiceNumber: 19
paymentTerms:
  line1: Net 30
  line2: 'Late Payment Fee: 1.5% per month'
postHeaders:
  clin: CLIN
  description: Location
  quantity: Amount
  rate: G&A
  total: Total
  type: Type
questions:
  line1: Joe Santorelli
  line2: joe.santorelli@mandaree.com
  line3: 478.714.0070
regions:
  Asia: '001'
  Europe: '002'
remitTo:
  line1: Accounts Receivable
  line2: MEC Energy Services
  line3: 23808 Andrew Road, Unit 3
  line4: Plainfield, IL 60585
upchargeRate: 0.35
version: 6
